services:
  db:
    restart: always
    image: postgres:latest
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - global

  web:
    restart: always
    build:
      dockerfile: ./Dockerfile-dev
      context: ./back/
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=back.settings
    volumes:
      - ./back:/app
      - /app/node_modules
    depends_on:
      - db
    networks:
      - global
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  pgdata:

networks:
  global:
