services:
  db:
    restart: always
    image: postgres:latest
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - global

  web:
    restart: always
    build:
      dockerfile: ./Dockerfile-dev
      context: ./back/
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=back.settings
      - SECRET_KEY=temp-key-will-be-replaced-by-postCreateCommand
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - ALLOWED_HOSTS=localhost,127.0.0.1,*.codespaces.dev,*.preview.app.github.dev
      - BASE_URL=http://localhost:8000
    volumes:
      - ./back:/app
      - /app/node_modules
    depends_on:
      - db
    networks:
      - global
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  pgdata:

networks:
  global:
