services:
  postgres:
    name: PostgreSQL Database
    description: PostgreSQL database for ChiefOnboarding
    triggeredBy:
      - postDevcontainerStart
    commands:
      start: |
        docker run --rm --name chiefonboarding-postgres \
          -e POSTGRES_DB=chiefonboarding \
          -e POSTGRES_USER=postgres \
          -e POSTGRES_PASSWORD=postgres \
          -p 5432:5432 \
          postgres:16
      ready: |
        timeout 60 bash -c 'until docker exec chiefonboarding-postgres pg_isready -U postgres; do sleep 1; done'

  redis:
    name: Redis Cache
    description: Redis for caching and background tasks
    triggeredBy:
      - postDevcontainerStart
    commands:
      start: |
        docker run --rm --name chiefonboarding-redis \
          -p 6379:6379 \
          redis:7-alpine
      ready: |
        timeout 30 bash -c 'until docker exec chiefonboarding-redis redis-cli ping | grep -q PONG; do sleep 1; done'

  playwright:
    name: Playwright Setup
    description: Install Playwright browsers and system dependencies for screenshots and testing
    triggeredBy:
      - postDevcontainerStart
    commands:
      start: |
        echo "Installing Playwright browsers..." && \
        bunx playwright install chromium && \
        echo "Installing system dependencies..." && \
        sudo apt-get update && \
        sudo apt-get install -y \
          libx11-6 libxext6 libxcb1 libglib2.0-0 libnspr4 libnss3 \
          libdbus-1-3 libatk1.0-0 libatk-bridge2.0-0 libcups2 \
          libxkbcommon0 libatspi2.0-0 libxcomposite1 libxdamage1 \
          libxfixes3 libxrandr2 libgbm1 libcairo2 libpango-1.0-0 \
          libasound2t64 && \
        echo "Creating version symlinks for compatibility..." && \
        ln -sf /home/vscode/.cache/ms-playwright/chromium-1194 \
          /home/vscode/.cache/ms-playwright/chromium-1179 && \
        ln -sf /home/vscode/.cache/ms-playwright/chromium_headless_shell-1194 \
          /home/vscode/.cache/ms-playwright/chromium_headless_shell-1179 && \
        echo "Playwright setup complete!"
      ready: |
        test -d /home/vscode/.cache/ms-playwright/chromium-1194

  django:
    name: Django Development Server
    description: Django web application with hot reload and database setup
    triggeredBy:
      - postDevcontainerStart
    commands:
      start: |
        export PATH="/home/vscode/.local/bin:$PATH" && \
        echo "Installing dependencies..." && \
        if ! command -v uv &> /dev/null; then
          curl -LsSf https://astral.sh/uv/install.sh | sh && \
          export PATH="/home/vscode/.local/bin:$PATH"
        fi && \
        uv sync && \
        echo "Setting up database..." && \
        if [ ! -f back/.env ]; then \
          echo "Creating .env file from .env.example..." && \
          cp back/.env.example back/.env; \
        fi && \
        echo "Waiting for PostgreSQL to be ready..." && \
        timeout 60 bash -c 'until docker exec chiefonboarding-postgres pg_isready -U postgres 2>/dev/null; do echo "Waiting for database..."; sleep 2; done' && \
        echo "PostgreSQL is ready!" && \
        echo "Running migrations..." && \
        uv run python back/manage.py migrate && \
        echo "Collecting static files..." && \
        uv run python back/manage.py collectstatic --noinput && \
        echo "Setting up development environment..." && \
        uv run python back/manage.py setup_dev_environment && \
        echo "Database ready, starting Django server..." && \
        gitpod environment port open --name django 8000 && \
        uv run python back/manage.py runserver 0.0.0.0:8000
      ready: |
        timeout 60 bash -c 'until curl -s http://localhost:8000 > /dev/null; do sleep 1; done'

tasks:
  run-tests:
    name: Run Tests
    description: Run the test suite
    triggeredBy:
      - manual
    command: |
      export PATH="/home/vscode/.local/bin:$PATH" && \
      uv run pytest back

  lint:
    name: Lint Code
    description: Run ruff linter
    triggeredBy:
      - manual
    command: |
      export PATH="/home/vscode/.local/bin:$PATH" && \
      uv run ruff check back

  format:
    name: Format Code
    description: Format code with ruff
    triggeredBy:
      - manual
    command: |
      export PATH="/home/vscode/.local/bin:$PATH" && \
      uv run ruff format back
